# Deploy Taskception to GitHub Pages
# 
# Security Features:
# - Actions pinned to full commit SHA (not tags) to prevent supply chain attacks
# - Minimal token permissions using permissions block
# - Job timeout to prevent runaway processes
# - Concurrency controls to prevent overlapping deployments
# - Secure environment configuration

name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# Prevent concurrent deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

# Minimal required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout repository code
      # Pinned to commit SHA for security (actions/checkout v4.2.2)
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      
      # Setup Node.js environment  
      # Pinned to commit SHA for security (actions/setup-node v4.1.0)
      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '18'
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Configure GitHub Pages
      # Pinned to commit SHA for security (actions/configure-pages v5.0.0)
      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b
        with:
          static_site_generator: custom
      
      # Build the application
      - name: Build
        run: npm run build
        env:
          # Set base path for GitHub Pages deployment
          VITE_BASE_PATH: ${{ github.event.repository.name == github.event.repository.owner.login && '/' || format('/{0}/', github.event.repository.name) }}
          # Supabase configuration (optional - app falls back to local storage if not provided)
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      
      # Upload build artifacts for deployment
      # Pinned to commit SHA for security (actions/upload-pages-artifact v3.0.1)  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: ./dist

  # Deployment job
  deploy:
    # Only deploy on pushes to master (not PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    
    steps:
      # Deploy to GitHub Pages
      # Pinned to commit SHA for security (actions/deploy-pages v4.0.5)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e 